{% set version = "0.9.6" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: af8b36d5d4242ec1bd86925f0f664a610e7e94309686ef0874df6bc0867a0c3e

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - rust
    - {{ compiler('c') }}
    - {{native}}binutils

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
