{% set version = "0.12.2" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 9bba901cb81332e5b120e3bdd2d5445386b61e8a6312eebd48204b4dc03a27e7

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - rust
    - {{ compiler('c') }}
    - {{native}}binutils      # [win]

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
