travis:
  secure:
    BINSTAR_TOKEN: VVml/Vk/8lyfHhallAvWFKlwyBNSo8Ny/8xX9i82FM1tQeQh22lxDbBxCZoTd/YinOtM7bx4VUtl0JjmTc+Fanp0CUMpo5rgcW5ywSGUIdhRUR7TAW5FWTFyKqOYuFpSZbNju6K1ZBm3f6BCTxFTVbj2zyn9BhBTQ8ALckI8ATTEg3iToxYkZ3BoB9M7etChxeftIwfy8NEUk4LK41IiPEOhFoKN8NanjsPjDfFPf3VF4qS4fgMm2/YSFsFMiQnezx+vIqamDnP8eV3eYVyX2Eq+jENYpTgsNaJjMZHHCSigTZP/TibWxaTUTYFKJLyaRdL4HKH+19il4cCa6/q8mb1msFlBuU4kC3oYsR8rItSKT1UhwMcQJulVJ6Mvv9XmYjYThf9u2P/+Q/uMNTXjYTl88amD0nyqulBUR0n6+XshiyqZkP5x1l5TVoisxbQ5jHSNNPp3jFSD8vjbkORdDqnNRWWlmIq9V3Z/tG751PkMvGTRgXOuAlrdS7d5b9uINJF521s08u11CMgPfEUoedQ9sa1zUQHKKALujwvzMP3mD6TePTnsRh7W4tA1/YnNSgsCK6Q8YxvvnFqbKm819cD61BH26/yRfl/kU8XYH7gkrEdBDYRmBfQOtvL9XFZ5ItlVUP+bMkURqbZS4G4Ci1kri5iA9geHrZdedCxRROk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
